name: Snapshot
on:
  push:
    branches: [main]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for changesets to work properly

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      # can't set --ignore-scripts because Astro uses postinstall
      - run: npm ci --prefer-offline --no-audit --no-fund --loglevel error

      - run: npm run build

      - name: Publish to "latest"
        run: |
          npx changeset publish --access public

      - name: Extract "latest" version
        id: extract_latest_version
        run: |
          VERSION=$(npm pkg get version -w apps/owox | grep -oE '"[0-9]+\.[0-9]+\.[0-9]+"' | tr -d '"')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Check if container image with this "latest" version exists
        id: latest_image_exists
        run: |
          if docker manifest inspect ghcr.io/${{ github.repository }}:${{ steps.extract_latest_version.outputs.version }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

      - name: Build and push "latest" container image
        if: steps.latest_image_exists.outputs.exists == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ steps.extract_latest_version.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.extract_latest_version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest

      - name: Create dummy changeset
        run: |
          cat <<EOF > .changeset/snapshot-release.md
          ---
          "owox": minor
          ---
          Snapshot release
          EOF

      - name: Publish to "next"
        run: |
          npx changeset version --snapshot next
          npx changeset publish --no-git-tag --snapshot --tag next

      - name: Extract "next" version
        id: extract_next_version
        run: |
          VERSION=$(npm pkg get version -w apps/owox | grep -oE '"[0-9]+\.[0-9]+\.[0-9]+-next-[0-9]+"' | tr -d '"')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Build and push "next" container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=${{ steps.extract_next_version.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.extract_next_version.outputs.version }}
            ghcr.io/${{ github.repository }}:next
